awslabs/keras-apache-mxnet

keras/backend/mxnet_backend.py
tests/keras/backend/backend_test.py

Fixed bugs across operators in MXNet backend. Enabled Keras backend test.
Few operators are not supported in MXNet backend and corresponding tests are skipped for MXNet backend. I will create an issue in this repo to track them before merging this code.
With this, we will enable nightly tests for MXNet backend with Keras backend test.
@jiajiechen

Fix MXNet backend operator bugs. Enabled Keras backend tests

---

keras/backend/mxnet_backend.py
keras/layers/convolutional.py
keras/layers/normalization.py
tests/keras/backend/backend_test.py

Fix performance issue with Batchnorm layer.
This fix significantly reduce the performance difference between Keras+MXNet and MXNet alone.
All UTs/ITs pass.
Benchmarked on Resnet56 - CIFAR10 with this fix.
On CPU
Keras-MXNet is around 8% slower than MXNet 
On GPU
Keras-MXNet is around 12% slower than MXNet.

Fix performance issue - Batchnormalization

---

keras/backend/mxnet_backend.py
keras/engine/topology.py
tests/test_model_saving.py

* Fix issue - https://github.com/deep-learning-tools/keras/issues/32 for model saving and loading.
* Tested with save model architecture, weights and both together. Then load it back. Verified on MNIST_MLP, CIFAR_CNN, CIFAR_Resnet.
* Tested with "EarlyStopping", "ModelCheckpoint" callbacks as well to save the model pre-emptively and load it back.
* Enabled a failing test case for this use case.
@nswamy @karan6181 @roywei

Fix model - architecture, weights and both, load and save.

---

keras/backend/mxnet_backend.py
pytest.ini
tests/keras/backend/backend_test.py
tests/keras/layers/convolutional_test.py

Tested with existing convolution 3D example in keras/test directory and also with an end-to-end model on a manually generated dataset.
@sandeep-krishnamurthy  @roywei

Conv3d() operator implementation for Keras2.0 using MXNet backend

---

keras/backend/mxnet_backend.py
tests/keras/backend/backend_test.py
tests/keras/layers/convolutional_test.py

* Add Conv1D operator in mxnet backend.
* Enable test cases for Conv1D.
@deep-learning-tools/aws-deep-learning-team 
@roywei @karan6181

Add Conv1D support for MXNet backend

---

keras/backend/__init__.py
keras/backend/mxnet_backend.py
keras/layers/convolutional.py
tests/keras/utils/layer_utils_test.py

* Enable conv kernel to be of channels_first or channels_last based on user provided data_format. This makes conv operation with mxnet backend avoid many transpose operations due to always channels_last conv kernel enforced by keras engine.
* Make mxnet as default backend for Keras in this branch.
@deep-learning-tools/aws-deep-learning-team

Enable perf optimization in conv operator for mxnet backend

---

keras/layers/convolutional.py

* Conv kernel is expected to be always channels_last for TF, CNTK and Theano backend.
* This PR fixes bug in perf optimizataion for MXNet backend conv operator.

Fix conv kernel shape bug for TF backend.

---

keras/backend/mxnet_backend.py
keras/utils/training_utils.py

This PR makes Keras-MXNet interface for one and multi-GPU training same across other backends.
Post this PR, no need to manually pass context param, however, it is still supported.
* Add support for keras multi_gpu_model() API with MXNet backend
* Autoset GPU0 context when running on GPU machine
Tested with Resnet50 on CIFAR with following settings:
1. No context -> Use first available GPU i.e., GPU0
2. compile with keras.training_utils.multi_gpu_model(model, gpus=4) -> Use 4 gpus i.e., GPU0, GPU1, GPU2, GPU3
3. compile with keras.training_utils.multi_gpu_model(model, gpus=[0, 3]) -> Use 2 gpus i.e., GPU0, GPU3
@deep-learning-tools/aws-deep-learning-team

Add support for keras multi_gpu_model() API with MXNet backend

---

keras/backend/mxnet_backend.py
tests/keras/backend/backend_test.py
tests/keras/layers/convolutional_recurrent_test.py
tests/keras/layers/convolutional_test.py

* Adding 'SAME' padding mode for pool2d and pool3d operator.
* Enabled corresponding tests.
@deep-learning-tools/aws-deep-learning-team

Add SAME padding mode support for pooling operator.

---

keras/backend/mxnet_backend.py
tests/integration_tests/test_temporal_data_tasks.py
tests/keras/backend/backend_test.py
tests/keras/layers/convolutional_test.py
tests/keras/layers/recurrent_test.py
tests/keras/legacy/layers_test.py
tests/keras/optimizers_test.py

- Add run() operator in MXNet backend with unrolling and masking feature.
- Modified constant(), zeros_like(), and categorical_crossentropy() operator
- Enable test cases for run() operator with unrolling and masking feature.
@deep-learning-tools/aws-deep-learning-team @sandeep-krishnamurthy @roywei

Add rnn() operator for MXNet backend with unrolling and masking feature

---

keras/backend/mxnet_backend.py
keras/optimizers.py
tests/keras/optimizers_test.py

* Adding support for NAdam and Adamax optimizer for MXNet backend.
* Keras test cases pass for these optimizer.
* Cannot enable test cases because, it includes "constraints" for variables functionality, which is not supported by MXNet backend and tracked at - https://github.com/deep-learning-tools/keras/issues/18
@deep-learning-tools/aws-deep-learning-team

Adamax and NAdam optimizer for MXNet backend

---

keras/backend/mxnet_backend.py
tests/keras/layers/recurrent_test.py

* Fix multi_gpu API bug for CPU. With AWS DLAMI on a CPU instance, nvidia-smi command do not throw OSError (not known command), instead throws non-zero exit status. Handled the case.
* Enabled PEP8 builds and fix pep failures.
* Made data_format default to None, forcing bias_add Operator to see keras.json for data_format, if it is not provided by Keras engine.
@awslabs/aws-deep-learning-sdk  @roywei

Fix multi_gpu API bug for CPU. Fix PEP. Fix bias_add

---

benchmark/README.md
benchmark/scripts/benchmark_resnet.py
benchmark/scripts/logging_metrics.py
benchmark/scripts/models/lstm_synthetic.py
benchmark/scripts/models/lstm_text_generation.py
benchmark/scripts/models/resnet50_benchmark.py
benchmark/scripts/models/resnet50_benchmark_tf_keras.py
benchmark/scripts/models/timehistory.py
benchmark/scripts/run_benchmark.py
benchmark/scripts/run_mxnet_backend.sh
benchmark/scripts/run_tf_backend.sh
benchmark/scripts/run_tf_keras_backend.sh

- API to extract the metrics from a model test and save to a log file
- modified a test to have epoch as a runtime parameter(Makes in sync with benchmarkAI repo)
@sandeep-krishnamurthy @roywei @kalyc

Added API to extract metrics from a test and also added a runtime epoch parameter

---

keras/backend/mxnet_backend.py
keras/models.py
tests/test_model_saving.py

Adding support to save the model as MXNet model (sym, params). This allows users to train using Keras interface with MXNet backend, export the model as MXNet model, use native MXNet for inference. Users can also use any language binding of MXNet ex: Python/Scala/C++ for inference.
1. Train MLP Sequential Model for MNIST and infer with MXNet.
2. Train Resnet50_CIFAR10 Functional Model on Multi-GpU and infer with MXNet on CPU.
3. Train IMDB_LSTM Sequential Model and infer with MXNet.
@nswamy @roywei @kalyc

Support exporting model as MXNet model (sym, params).

---

docs/templates/getting-started/faq.md
docs/templates/why-use-keras.md
keras/__init__.py
keras/applications/imagenet_utils.py
keras/engine/topology.py
setup.py
tests/test_model_saving.py

Pulling in following 4 commits we had missed from keras-team/keras 2.1.6 release.
https://github.com/keras-team/keras/commit/b26fa3b63870b6160340bfeeb384b8d812dbbd15
https://github.com/keras-team/keras/commit/f0175de8296069c6c5c6e36c145da641f7aa5bc0
https://github.com/keras-team/keras/commit/30c34ff6327d04b1296a66f6d463d8c7b2f1a96b
https://github.com/keras-team/keras/commit/b09ec1c9bf827622a5eebb94ba0af5bf202ca359
@roywei @kalyc

Cherry pick keras-team/keras 2.1.6 missing 4 commits

---

keras/backend/mxnet_backend.py

* mx.sym.SoftmaxActivation operator crashes on GPUs - https://github.com/apache/incubator-mxnet/issues/9823. This issue is visible in mxnet v1.2.0 but not in earlier version.
* Move to mx.sym.softmax() operator that has the fix for softmax operator.
* Without this fix, with latest mxnet v1.2.0, none of the CNNs work.
* Verified on CPU and GPUs
@roywei @kalyc

Fix crashing softmax mxnet backend operator on GPUs

---

keras/backend/mxnet_backend.py
keras/engine/training.py
tests/keras/layers/normalization_test.py
tests/keras/legacy/layers_test.py
tests/keras/losses_test.py
tests/keras/utils/vis_utils_test.py
tests/test_loss_weighting.py
tests/test_model_saving.py

* Fix bug in Concat operator leading to failure in Layers.Concatenate.
* Fix shape mis-match errors when using Custom Loss.
* Enable 6 more unit tests.
@roywei @kalyanee

Fix custom loss for MXNet backend. Fix bug in Concat layer

---

keras/backend/mxnet_backend.py
tests/test_model_saving.py

* Adding a new API in MXNet backend - `data_names, data_shapes = get_mxnet_model_info(model)` for users to be able to query MXNet backend to see what is underlying MXNet model metadata. 
* This API is typically useful for users using MXNetModelCheckpoint to save best model as native MXNet model but, through checkpoint they can't get the MXNet model details. So they will use this API for fetching those details to bind to MXNet module.
@kalyc @roywei

Adding get_mxnet_model_info API to allow users to query underlying MXNet model info

---

keras/backend/mxnet_backend.py
keras/losses.py
tests/keras/backend/backend_test.py

* Support slicing the axis with '-1' indexing in tensors. Without this change we cannot slice a Keras Tensor with MXNet backend something like var[:, -1, :]
* Remove custom loss function warning, as the related MXNet slice and slice_axis issue https://github.com/awslabs/keras-apache-mxnet/issues/120 is resolved.
* This PR will fix - https://github.com/awslabs/keras-apache-mxnet/issues/113
* This PR will fix - https://github.com/awslabs/keras-apache-mxnet/issues/139
- [y] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n]
@roywei @kalyc

Support slicing axis in Keras Tensor with MXNet backend

---

keras/backend/mxnet_backend.py
tests/keras/backend/mxnet_sparse_test.py

Add sparse support for `concat` operator
[Missing sparse operators](https://github.com/awslabs/keras-apache-mxnet/issues/18)

Add sparse concat operator support

---

keras/metrics.py
tests/keras/legacy/interface_test.py
tests/keras/metrics_test.py

Fix https://github.com/awslabs/keras-apache-mxnet/issues/165
https://github.com/awslabs/keras-apache-mxnet/issues/165
1. sparse categorical acc should have the same result as categorical acc.
For example, with 3 classes, given `sparse_true_label = [0, 1, 1]`, it's equivalent in categorical labels is `dense_true_label = [[1, 0, 0], [0, 1, 0], [0, 1, 0]]`. With the same predictions 
```
pred = [[0.7, 0.2, 0.1], 
[0.1, 0.1, 0.8], 
[0.2, 0.6, 0.2]]
```
They should produce the same acc which is `[1, 0 ,1]`
2. Not sure why `max` is used, but it should directly compare with `y_true`
3. Added unit test to test correctness

fix sparse acc

---

examples/multi_hot_sparse_categorical_crossentropy.py
keras/backend/mxnet_backend.py
keras/engine/training.py
keras/engine/training_utils.py
keras/losses.py
keras/metrics.py
keras/utils/np_utils.py
tests/keras/losses_test.py
tests/keras/metrics_test.py

This PR adds a new feature to calculate categorical cross-entropy on multi hot sparse labels
Inputs are softmax predictions and true labels.
It should return same loss as categorical cross-entropy.
Example:
```
Input:
input data is random images of size (32, 32) in channels first data format
Labels:
Tradition labels are in the shape of (num_samples, num_class), for example:
labels = [[0, 1, 1, ..., 0],
[1, 1, 0, ..., 0],
...
[0, 0, 0, ..., 1]]
where len(labels) = num_samples, len(labels[0]) = num_classes
However, when num_classes are very large and labels are very sparse,
we can represent them differently, for example:
There are total 1000 classes, so there will be 10000 different labels.
Each image can belong to at most 5 labels at the same time.
labels = [[1, 2],
[0, 1],
...
[999]] …
```

Add multi hot sparse categorical crossentropy

---

keras_mxnet_ci/nightly-buildspec.yml
keras_mxnet_ci/pr-buildspec.yml

- Note this change is directly going to master branch since it's a change on CI
- Changing PR builds to use the latest mxnet master (pip install mxnet-mkl --pre) so development is not blocked by mxnet release. We can test with mxnet latest features in PR build on dev branch
- Nightly build still remains to test with mxnet stable release

test PR build with latest mxnet master

---

keras/backend/mxnet_backend.py
tests/keras/backend/mxnet_sparse_test.py
tests/keras/engine/test_training.py

Fix bug in is_sparse() method, enable sparse test in training
Disable sparse concat test for testing CI build
Examples were failing locally - verified that they work locally now
Unit tests were also failing locally under test_training - verified that they pass now
- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n]

Fix bug in is_sparse() method, enable sparse test in training

---

keras/engine/training_utils.py
tests/keras/backend/mxnet_sparse_test.py

Fix failing unit test in test_documentation.
One parameter is missing documentation in doc string.
This unit test was not captured due to codebuild not reporting test failing correctly

fix documentation, temporary disable sparse_concat test

---

docs/mxnet_backend/prepare_sparse_data_for_training.md

We added `prepare_sliced_sparse_data` API for being able to slice the sparse training data as MXNet doesn't support `reshape`
Adding documentation to help users use the API 
https://github.com/awslabs/keras-apache-mxnet/pull/170

Add documentation on using the prepare_sliced_sparse_data API

---

benchmark/sparse/linear_regression/keras_sparse_model.py
benchmark/sparse/linear_regression/keras_tf_model.py
benchmark/sparse/linear_regression/mxnet_sparse_model.py
benchmark/sparse/linear_regression/results.md
benchmark/sparse/linear_regression/run_sparse_benchmark.py
keras/backend/mxnet_backend.py
keras/utils/data_utils.py
tests/keras/utils/data_utils_test.py

Keras-MXNet benchmark script resulted in segmentation fault error initially. Added check to ensure that it doesn't happen. 
`Note` - 
Benchmark script currently works well only with batch size <= (10) train_data.shape[1] size
For dimensions > 10 this is the error we get - 
`
File "benchmark/sparse/linear_regression/run_sparse_benchmark.py", line 40, in <module>
invoke_benchmark(args.batch, args.epochs)
File "benchmark/sparse/linear_regression/run_sparse_benchmark.py", line 25, in invoke_benchmark
epochs=int(epochs))
File "/Users/kalyanee/Documents/kalyc-keras-1/keras-apache-mxnet/benchmark/sparse/linear_regression/keras_sparse_model.py", line 26, in run_benchmark
batch_size=batch_size)
File "/anaconda2/envs/mxnet/lib/python3.4/site-packages/keras_mxnet-2.2.2-py3.4.egg/keras/engine/training …

Fix sparse benchmark

---

keras/backend/mxnet_backend.py
keras/layers/embeddings.py
tests/keras/backend/mxnet_sparse_test.py
tests/keras/layers/embeddings_test.py

Add minimal test for testing sparse embedding operator support
[Missing Sparse operator support](https://github.com/awslabs/keras-apache-mxnet/issues/18)
- [y] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n]

Add Sparse embedding support

---

docs/mxnet_backend/using_rnn_with_mxnet_backend.md
examples/imdb_lstm.py
keras/backend/mxnet_backend.py
keras/layers/recurrent.py
tests/keras/layers/recurrent_test.py
tests/test_model_saving.py

- Add control flow ops in RNN so we can set unroll=False as default
- resolved drop out issue: https://github.com/awslabs/keras-apache-mxnet/issues/60
- enabled 18 rnn unit tests
https://github.com/awslabs/keras-apache-mxnet/wiki/Using-RNN-with-MXNet-backend
https://github.com/awslabs/keras-apache-mxnet/issues/60

Full RNN support with control flow ops

---

keras/backend/mxnet_backend.py
tests/test_model_saving.py

fix https://github.com/awslabs/keras-apache-mxnet/issues/138
- If we load pre-trained weight and do some training, after that, when saving weights will not save updated weights. It's because we didn't get the latest weights (_arg_params) in bucketing module. 
- fixed with new get_arg_param method when saving weights
- added unit test for testing fine-tune use case.
https://github.com/awslabs/keras-apache-mxnet/issues/138

Fix save weight for fine tune

---

pytest.ini

Recently nightly test failed due to timeout.
keras added this limitation for single unit tests, but we are using different CI systems and instance types.
Increased timeout for a single unit test to 20 mins maximum

increase timeout limit

---

benchmark/sparse/linear_regression/inference_benchmark.md

Update units for inference benchmark to be samples/sec
Fix https://github.com/awslabs/keras-apache-mxnet/issues/204

Update units for inference benchmark to be samples/sec

---

keras/backend/mxnet_backend.py

mxnet 1.3.1 was released, no longer require to install nightly build of mxnet to use control flow ops in Keras.

no longer require --pre for 1.3.1

---

keras/backend/mxnet_backend.py

nightly test failed due to an update from MXNet side on SGD optimizer:
https://github.com/apache/incubator-mxnet/pull/13346
changed SGD optimizer in mxnet backend accordingly, and set aggregate_num=1, as Keras optimizer do it 1 at a time.

fix nightly on sgd

---

tests/keras/layers/recurrent_test.py

There is an issue with the Masking Layer in RNN with MXNet backend after this PR [#14192](https://github.com/apache/incubator-mxnet/pull/14192) got merged into MXNet [master](https://github.com/apache/incubator-mxnet/) branch. Ignoring those test for now to let the nightly build pass. I have created a separate issue [#228](https://github.com/awslabs/keras-apache-mxnet/issues/228) to track the masking layer issue.

Ignoring masking layer test for RNN with MXNet backend

---

keras/activations.py

https://github.com/apache/incubator-mxnet/pull/14869 fix nightly test failure after unknown dim changed from 0 to -1 in MXNet.
This fix softmax shape check in keras after the change.
requires https://github.com/apache/incubator-mxnet/pull/14869 to go into nightly pip packages to pass CI.

fix softmax shape

---

keras_mxnet_ci/nightly-buildspec-python2.yml
keras_mxnet_ci/nightly-buildspec-python3.yml

fix nightly build on Python3
keras`setup.py` does not require any version on `pytest` `pyyaml` and `pytest-xdist`. So our  CI is picking up the latest version. However, it's causing tests to fail.
Ping them to older stable versioni resolves the issue.

ping pytest version in ci

---

keras/activations.py
keras/backend/mxnet_backend.py
keras/datasets/boston_housing.py
keras/datasets/imdb.py
keras/datasets/reuters.py

test_imdb is failing deterministically due to numpy update on 1.16, we have to specify `allow_pickle` as True

fix test dataset

---

keras_mxnet_ci/nightly-buildspec-python2.yml
keras_mxnet_ci/nightly-buildspec-python3.yml
keras_mxnet_ci/pr-buildspec-python2.yml
keras_mxnet_ci/pr-buildspec-python3.yml

ping tf version in ci

---

keras_mxnet_ci/nightly-buildspec-python2.yml
keras_mxnet_ci/nightly-buildspec-python3.yml
keras_mxnet_ci/pr-buildspec-python2.yml
keras_mxnet_ci/pr-buildspec-python3.yml

Using Python3.7 for python 3 tests. It seems the latest stable 1.x tensorflow is 1.15 and only available for python3.7 (not 3.6/3.5).
Updated to use python3.7 environment in AWS code build.
change install commands to use python3.7 as the default python3 is python3.5 on the code build environment.

update to python 3.7

---

keras/backend/mxnet_backend.py
keras/engine/network.py
tests/keras/backend/mxnet_context_test.py

fix https://github.com/awslabs/keras-apache-mxnet/issues/251
This PR fix it, and added the following:
1. set MXNet context during Model class initialization using context kwargs
2. set MXNet context during model.compile() through context kwargs
3. set MXNet context using model.set_mxnet_context(context)
context supports single context or list of context, for example `'cpu'` or `'gpu(0)'` or `['gpu(1)', 'gpu(2)']`
Added tests at: `tests/keras/backend/mxnet_context_test.py`

fix set MXNet context

---

keras/backend/mxnet_backend.py
keras/layers/normalization.py
tests/keras/backend/mxnet_operator_test.py

As per user feedback, Keras-MXNet was not able to freeze the running mean and var weights during fine tune.
This PR fix the bug and added unit test
Reference:
https://discuss.mxnet.io/t/how-freeze-batchnorm-layer-in-symbolblock/3949

fix batchnorm freeze mean and var

---

keras/engine/network.py
keras/layers/normalization.py

1. Fix kwargs
In https://github.com/awslabs/keras-apache-mxnet/pull/250, I added `**kwargs` in `_init_subclassed_network` inorder to fix MXNet context problem, and it's not enough.
This PR brings more `**kwargs` in Keras front end to fix `**kwargs` not passed along in subsequent `_base_init `  method.
These changed are already made in official upstream Keras front end, and will be updated during next merge.
2. Updated comments to properly fix moving mean and var for BatchNorm layer

fix kwargs and add comments

---

keras/layers/normalization.py
tests/keras/backend/mxnet_tf_model_test.py

Fix axis error in normalization layer when loading model from tf backend saved h5
When loading model saved by tensorflow backend keras h5 file, met an error:
```sh
/opt/anaconda3/lib/python3.7/site-packages/keras/layers/normalization.py in build(self, input_shape)
98
99     def build(self, input_shape):
--> 100         dim = input_shape[self.axis]
101         print(input_shape, self.axis, dim)
102         if dim is None
TypeError: tuple indices must be integers or slices, not list
```
I write a little demo to reproduce it:
- Save a tensorflow backend keras h5 model file:
```py
from tensorflow import keras
mm = keras.models.Sequential([
keras.layers.Dense(10, kernel_initializer="zeros"),
keras.layers.BatchNormalization()])
mm.build(input_shape=(1, 10))
mm.summary()
mm.layers[-1].axis  # …
```

Fix axis error in normalization layer when loading model from tf backend saved h5
